name: Run test

on: 
  push:
  pull_request:
jobs:
  test:
  runs-on: ubuntu-latest
steps:
- name: Dowload the code
  user: actions/checkout@v4\
- name: Install Python
  user: actions/setup-python@v5
with:
     python-version: "3.11"
- name: Install requirements
  run: 
      python -m pip install --upgrade pip
      pip instal -r requirements.txt
- name: Run test
  run: pytest
